base.api.url=https://api.clockify.me/api
crowdar.projectType=API
crowdar.api=true
crowdar.api.entityConfiguration=api.config.EntityConfiguration
environment=
apiKey=YTFlNWYzOGUtODdkYS00NzI3LWJkZjYtNDM1ZDRiMTUyYmIx

test-manager.screenshots = DISABLED

crowdar.extent.host.name=LocalMachine
crowdar.extent.environment=Local
crowdar.extent.user.name=User.name